source 'https://github.com/CocoaPods/Specs.git'

target 'iTunesApi' do
  pod "iTunesApi", :path => "../"
  
  pod 'AFNetworking'
  pod 'RestKit'
  
  
end

target 'Tests' do
  pod "iTunesApi", :path => "../"

  pod 'Specta', '~> 0.2.1'
  pod 'Expecta'
end
