source 'https://github.com/CocoaPods/Specs.git'

target 'iTunesApi', :exclusive => true do
  pod "iTunesApi", :path => "../"
  
  pod 'AFNetworking', '~> 1.3.4'
  pod 'RestKit', '~> 0.23.1'
  
  
end

target 'Tests', :exclusive => true do
  pod "iTunesApi", :path => "../"

  pod 'Specta', '~> 0.2.1'
  pod 'Expecta'
end
